### ISSUE TITLE
Swiss and Vatican flag should be a square

### ISSUE THREAD

**Issue by christianruhstaller** [growthbunker/vueflags#1]
Swiss flag:

Since January 1st, 2017 the Swiss Flag is required by law to be square:
"The Swiss flag shows a Swiss cross on a square background."
https://www.admin.ch/opc/en/classified-compilation/20091656/index.html#a3
https://www.admin.ch/opc/en/classified-compilation/20091656/index.html#app2

Just the flag on the sea has the proportions of 2:3.
https://www.admin.ch/opc/de/classified-compilation/19530141/index.html#app1ahref0

Vatican flag:
https://en.wikipedia.org/wiki/Flag_of_Vatican_City

**Comment by LeCoupa** [comment]
Hello,

Thank you for the information @christianruhstaller. Unfortunately, I am using [this icon pack](https://www.flaticon.com/packs/countrys-flags) and I do not plan on redesigning them.
