### ISSUE TITLE
Importing into quasar

### ISSUE THREAD

**Issue by Quasarman** [growthbunker/vueflags#2]
Hello how would I achive importing this plugin into the quasar framework?

**Comment by LeCoupa** [comment]
Hello, I have never used the Quasar Framework. Did you succeed at importing the component like any other one?

```
npm install @growthbunker/vueflags
```

And then in your `main.js` file:

```javascript
import Vue from "vue"
import VueFlags from "@growthbunker/vueflags"

Vue.use(VueFlags)
```

And in one component file:

```html
<template>
  <gb-flag code="fr" size="small" />
</template>
```

**Comment by Quasarman** [comment]
Yeah I read the documentation. I tried it like you stated but it dosent seem to work. Quasar does use something like boot files where you can do Vue.use() but then i somehow need to register the component it seems. I am really new to quasar and vue maybe I am overlooking something.
But thanks for your reply anyways

**Comment by LeCoupa** [comment]
If you can register your plugin with `Vue.use()` on Qasar, I don't see any reasons why this library would not work. :)

I am closing the issue.
