### ISSUE TITLE
Indian Flag Issue

### ISSUE THREAD

**Issue by Ruchirr** [growthbunker/vueflags#7]
Hi, Thank you for providing .svg flags for Vue. Though, I have an issue.

The flag you have deployed for India is invalid in vueflags/assets/flags/in.svg. It is not an Indian flag. I request you to please change the flag to the one that I have shared below from the source of wikipedia or as per your wished open source. Furthermore, the Indian flag has 'Ashok Chakra' in between and not the star. I thank you in advance for the same.

Your flag:

> Link:

 https://github.com/growthbunker/vueflags/blob/master/assets/flags/in.svg

> Svg:

`<?xml version="1.0" encoding="iso-8859-1"?>
<svg
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
  <rect y="85.337" style="fill:#F0F0F0;" width="512" height="341.326"/>
  <rect y="85.337" style="fill:#FF9811;" width="512" height="113.775"/>
  <rect y="312.888" style="fill:#6DA544;" width="512" height="113.775"/>
  <circle style="fill:#0052B4;" cx="256" cy="256" r="43.896"/>
  <circle style="fill:#F0F0F0;" cx="256" cy="256" r="27.434"/>
  <polygon style="fill:#0052B4;" points="256,222.146 264.464,241.341 285.319,239.073 272.927,256 285.319,272.927 264.464,270.659   256,289.854 247.536,270.659 226.681,272.927 239.073,256 226.681,239.073 247.536,241.341 "/>
</svg>
`

Real Indian Flag:

> Link:

 https://en.wikipedia.org/wiki/File:Flag_of_India.svg#/media/File:Flag_of_India.svg

> Svg:

`<?xml version="1.0" encoding="UTF-8"?>
<svg width="1350" height="900" viewBox="0 0 225 150" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<rect width="225" height="150" fill="#f93"/>
<rect y="50" width="225" height="100" fill="#fff"/>
<rect y="100" width="225" height="50" fill="#128807"/>
<g transform="translate(112.5,75)">
<circle r="20" fill="#008"/>
<circle r="17.5" fill="#fff"/>
<circle r="3.5" fill="#008"/>
<g id="e">
<g id="f">
<g id="g">
<g id="h">
<circle transform="rotate(7.5) translate(17.5)" r=".875" fill="#008"/>
<path d="m0 17.5 0.6-10.5-0.6-5-0.6 5 0.6 10.5z" fill="#008"/>
</g>
<use transform="rotate(15)" xlink:href="#h"/>
</g>
<use transform="rotate(30)" xlink:href="#g"/>
</g>
<use transform="rotate(60)" xlink:href="#f"/>
</g>
<use transform="rotate(120)" xlink:href="#e"/>
<use transform="rotate(240)" xlink:href="#e"/>
</g>
</svg>
`

**Comment by LeCoupa** [comment]
Thank you @Ruchirr,  I have updated it with your flag. 👍 

Update your package to `0.0.9`.

**Comment by Ruchirr** [comment]
Hi @LeCoupa 

Thanks for a quick update. Though, the svg compilation does not match with other flags. This is how it is looking figure 1. Before with the wrong flag it was working just fine figure 2

Figure 1

<img width="1064" alt="Screen Shot 2020-05-23 at 7 43 01 pm" src="https://user-images.githubusercontent.com/30252229/82727426-d8867100-9d2d-11ea-828e-706ed2849448.png">

Figure 2

<img width="942" alt="Screen Shot 2020-05-23 at 7 46 16 pm" src="https://user-images.githubusercontent.com/30252229/82727465-1be0df80-9d2e-11ea-9e43-924c52bf95f1.png">

**Comment by Ruchirr** [comment]
Please use the following SVG code

`<?xml version="1.0" encoding="iso-8859-1"?>
<svg
  xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">

  <path fill-rule="evenodd" clip-rule="evenodd" d="M0 141.836V198.672H256H512V141.836V85H256H0V141.836ZM128.027 312.583C198.529 312.626 313.801 312.626 384.187 312.583C454.572 312.538 396.888 312.501 256 312.501C115.112 312.501 57.5232 312.538 128.027 312.583Z" fill="#FC9C34"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M0 255.506V312.342H256H512V255.506V198.672H256H0V255.506ZM265.125 210.994C300.822 218.893 313.747 262.247 288.044 287.858C270.112 305.723 241.775 305.656 223.799 287.704C197.638 261.575 212.052 217.144 248.795 210.65C252.083 210.07 261.88 210.276 265.125 210.994ZM252.474 217.016C251.608 218.395 250.363 218.545 249.299 217.397L248.513 216.55L245.874 217.234C242.705 218.055 242.712 218.052 242.712 218.973C242.712 220.492 240.475 221.365 239.383 220.273C238.513 219.401 233.327 222.343 233.627 223.537C234.047 225.209 232.34 226.678 230.885 225.899C229.786 225.311 225.224 229.342 226.052 230.17C226.55 230.667 226.447 232.181 225.878 232.749C225.361 233.266 225.192 233.319 223.82 233.378C222.456 233.438 219.788 238.185 220.639 239.037C221.855 240.253 220.776 242.539 218.986 242.539C218.557 242.539 218.267 242.988 217.901 244.219C216.987 247.289 216.94 248.23 217.668 248.858C218.944 249.961 218.445 252.465 216.95 252.465C216.402 252.465 216.143 253.49 216.143 255.666C216.143 257.844 216.402 258.869 216.95 258.869C218.445 258.869 218.944 261.373 217.668 262.475C216.94 263.105 216.987 264.045 217.901 267.113C218.267 268.346 218.557 268.795 218.986 268.795C220.776 268.795 221.855 271.08 220.639 272.296C219.784 273.151 222.46 277.903 223.82 277.946C225.128 277.987 225.35 278.056 225.878 278.584C226.437 279.143 226.552 280.664 226.072 281.145C225.248 281.968 229.793 286.019 230.885 285.434C232.361 284.644 234.14 286.262 233.614 287.917C233.464 288.392 233.836 288.749 235.427 289.666C238.822 291.619 238.824 291.62 239.38 291.065C240.497 289.947 242.712 290.846 242.712 292.417C242.712 293.277 242.726 293.284 245.874 294.1L248.513 294.785L249.299 293.936C250.363 292.789 251.608 292.939 252.474 294.319L253.119 295.346H256H258.881L259.526 294.319C260.388 292.945 261.637 292.789 262.689 293.924L263.464 294.759L265.495 294.288C268.695 293.545 269.288 293.249 269.288 292.387C269.288 290.842 271.514 289.959 272.62 291.065C273.175 291.62 273.179 291.619 276.563 289.671C278.263 288.694 278.529 288.42 278.376 287.809C277.953 286.125 279.653 284.652 281.115 285.434C282.207 286.019 286.752 281.968 285.928 281.145C285.448 280.664 285.563 279.143 286.122 278.584C286.65 278.056 286.872 277.987 288.18 277.946C289.54 277.903 292.216 273.151 291.361 272.296C290.145 271.08 291.224 268.795 293.014 268.795C293.443 268.795 293.733 268.346 294.099 267.113C295.013 264.045 295.06 263.105 294.332 262.475C293.056 261.373 293.555 258.869 295.05 258.869C295.598 258.869 295.857 257.844 295.857 255.666C295.857 253.49 295.598 252.465 295.05 252.465C293.555 252.465 293.056 249.961 294.332 248.858C295.06 248.23 295.013 247.289 294.099 244.219C293.733 242.988 293.443 242.539 293.014 242.539C291.224 242.539 290.145 240.253 291.361 239.037C292.212 238.185 289.544 233.438 288.18 233.378C286.808 233.319 286.639 233.266 286.122 232.749C285.563 232.191 285.448 230.669 285.928 230.189C286.752 229.366 282.207 225.315 281.115 225.899C279.653 226.682 277.953 225.209 278.376 223.524C278.529 222.914 278.263 222.64 276.563 221.662C273.179 219.715 273.175 219.714 272.62 220.269C271.492 221.397 269.288 220.486 269.288 218.891C269.288 218.093 268.631 217.773 265.495 217.046L263.464 216.574L262.689 217.41C261.637 218.545 260.388 218.389 259.526 217.016L258.881 215.986H256H253.119L252.474 217.016ZM256.791 228.634C257.388 238.956 257.402 240.159 256.96 243.503C256.371 247.971 256.362 247.661 257.069 247.661C257.576 247.661 257.729 247.147 258.182 243.899C258.653 240.527 265.564 217.895 265.993 218.324C266.433 218.764 261.388 240.826 260.129 243.966C258.584 247.816 258.464 248.4 259.247 248.246C259.574 248.181 260.394 246.723 261.409 244.404C262.84 241.132 274.918 221.848 275.31 222.206C275.74 222.599 265.106 242.699 262.993 245.489C260.854 248.314 260.298 249.583 261.203 249.583C261.347 249.583 262.468 248.273 263.695 246.671C265.629 244.146 282.44 228.45 283.21 228.45C283.95 228.45 267.694 245.883 265.015 247.962C262.646 249.801 262.025 250.44 262.291 250.761C262.698 251.252 262.575 251.32 266.257 248.593C268.713 246.776 289.14 236.047 289.14 236.575C289.14 237.145 269.587 249.371 266.789 250.55C263.245 252.045 263.119 252.129 263.494 252.735C263.68 253.036 264.622 252.775 267.284 251.684C270.413 250.403 290.924 245.64 292.774 245.766C294.042 245.851 271.987 252.849 269.128 253.268C264.042 254.014 263.845 254.063 263.845 254.561C263.845 255.137 264.878 255.156 268.786 254.651C271.735 254.271 294.264 255.169 294.264 255.666C294.264 256.164 271.735 257.062 268.786 256.681C264.878 256.177 263.845 256.196 263.845 256.774C263.845 257.272 264.042 257.32 269.128 258.065C271.987 258.485 294.042 265.483 292.774 265.569C290.924 265.693 270.413 260.931 267.284 259.65C264.622 258.559 263.68 258.298 263.494 258.599C263.119 259.206 263.245 259.289 266.789 260.783C269.587 261.963 289.14 274.188 289.14 274.759C289.14 275.286 268.713 264.559 266.257 262.74C262.575 260.015 262.698 260.082 262.291 260.573C262.025 260.894 262.646 261.533 265.015 263.371C267.694 265.449 283.95 282.884 283.21 282.884C282.44 282.884 265.629 267.188 263.695 264.662C262.468 263.061 261.347 261.75 261.203 261.75C260.298 261.75 260.854 263.02 262.993 265.844C265.105 268.633 275.741 288.738 275.31 289.126C274.897 289.499 262.597 269.78 261.198 266.499C260.067 263.847 259.475 262.81 259.163 262.93C258.513 263.18 258.587 263.524 260.129 267.368C261.39 270.513 266.433 292.57 265.992 293.012C265.565 293.438 258.66 270.813 258.185 267.435C257.729 264.189 257.576 263.672 257.069 263.672C256.362 263.672 256.371 263.362 256.96 267.833C257.402 271.175 257.389 272.364 256.801 282.381C256.449 288.382 256.15 293.579 256.136 293.931C256.054 295.943 255.786 292.694 255.209 282.7C254.612 272.378 254.598 271.174 255.04 267.83C255.629 263.362 255.638 263.672 254.931 263.672C254.424 263.672 254.271 264.189 253.815 267.435C253.34 270.813 246.435 293.438 246.008 293.012C245.567 292.57 250.61 270.513 251.871 267.368C253.413 263.524 253.487 263.18 252.837 262.93C252.525 262.81 251.933 263.847 250.803 266.499C249.448 269.681 238.324 287.59 236.55 289.448C235.142 290.924 246.929 268.589 249.007 265.844C251.146 263.02 251.702 261.75 250.797 261.75C250.653 261.75 249.532 263.064 248.305 264.669C246.365 267.204 229.571 282.884 228.794 282.884C228.186 282.884 244.259 265.475 246.396 263.819C247.75 262.769 249.143 261.685 249.492 261.41C250.03 260.985 250.058 260.853 249.672 260.533C249.307 260.23 248.631 260.598 246.205 262.424C243.571 264.406 221.734 275.897 223.02 274.625C224.687 272.972 242.034 262.205 245.152 260.886C247.15 260.04 248.785 259.277 248.786 259.189C248.787 258.224 248.084 258.31 244.64 259.695C241.384 261.004 218.908 266.184 218.423 265.737C218.071 265.414 241.24 258.242 243.672 257.923C247.625 257.405 248.155 257.268 248.155 256.762C248.155 256.204 247.451 256.193 243.473 256.681C240.381 257.062 218.377 256.172 218.377 255.666C218.377 255.162 240.381 254.273 243.473 254.653C247.451 255.142 248.155 255.129 248.155 254.572C248.155 254.066 247.625 253.929 243.672 253.411C241.24 253.091 218.071 245.921 218.423 245.597C218.908 245.15 241.384 250.33 244.64 251.64C248.081 253.022 248.803 253.11 248.782 252.145C248.781 252.057 247.09 251.259 245.025 250.374C241.921 249.041 221.955 236.612 222.324 236.242C222.642 235.925 244.015 247.224 246.088 248.804C249.318 251.268 249.297 251.257 249.709 250.761C249.975 250.44 249.354 249.801 246.985 247.962C244.3 245.878 228.05 228.45 228.794 228.45C229.571 228.45 246.365 244.129 248.305 246.665C249.532 248.271 250.653 249.583 250.797 249.583C251.702 249.583 251.146 248.314 249.007 245.489C246.929 242.745 235.142 220.41 236.55 221.886C238.223 223.638 249.443 241.644 250.715 244.62C251.656 246.822 252.42 248.181 252.75 248.246C253.536 248.4 253.417 247.819 251.871 243.966C250.61 240.821 245.567 218.763 246.008 218.322C246.435 217.896 253.34 240.521 253.815 243.899C254.271 247.145 254.424 247.661 254.931 247.661C255.638 247.661 255.629 247.972 255.04 243.501C254.598 240.158 254.611 238.97 255.199 228.952C255.551 222.952 255.85 217.755 255.864 217.403C255.946 215.391 256.214 218.64 256.791 228.634Z" fill="#FBFBFB"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M0 369.498V426.334H256H512V369.498V312.662H256H0V369.498Z" fill="#0C8C04"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M250.912 210.538C214.595 214.752 197.805 258.302 221.948 285.667C249.586 316.991 301.143 297.461 301.143 255.666C301.143 228.314 277.874 207.41 250.912 210.538ZM258.336 215.836C259.016 215.972 259.369 216.266 259.505 216.808C259.891 218.348 262.076 218.432 262.876 216.938C263.195 216.343 263.274 216.347 266.108 217.105C267.707 217.532 269.076 217.883 269.151 217.883C269.226 217.883 269.288 218.243 269.288 218.683C269.288 220.378 271.323 221.342 272.552 220.228C273.618 219.264 278.767 222.193 278.422 223.569C277.999 225.252 280.21 226.686 281.399 225.497C282.22 224.676 286.445 229.47 285.951 230.661C285.334 232.151 286.2 233.367 287.75 233.186C288.995 233.041 289.157 233.207 291.043 236.552C292.012 238.274 292.051 238.454 291.576 238.979C290.42 240.255 291.11 242.218 292.714 242.218C293.519 242.218 293.652 242.396 294.212 244.219C295.363 247.971 295.377 248.25 294.452 248.978C293.119 250.026 293.77 252.465 295.384 252.465C295.78 252.465 295.864 253.033 295.864 255.666C295.864 258.299 295.78 258.869 295.384 258.869C293.77 258.869 293.119 261.307 294.452 262.355C295.377 263.084 295.363 263.362 294.212 267.113C293.652 268.937 293.519 269.115 292.714 269.115C291.11 269.115 290.42 271.077 291.576 272.354C292.051 272.88 292.012 273.06 291.043 274.78C289.157 278.125 288.995 278.293 287.75 278.147C286.2 277.966 285.334 279.181 285.951 280.671C286.445 281.863 282.22 286.656 281.399 285.836C280.21 284.648 277.999 286.08 278.422 287.765C278.767 289.139 273.618 292.069 272.552 291.104C271.323 289.992 269.288 290.956 269.288 292.649C269.288 293.09 269.226 293.45 269.151 293.45C269.076 293.45 267.707 293.8 266.108 294.227C263.274 294.986 263.195 294.99 262.876 294.395C262.076 292.901 259.891 292.985 259.505 294.524C259.089 296.186 252.911 296.186 252.495 294.524C252.109 292.985 249.924 292.901 249.124 294.395C248.805 294.99 248.726 294.986 245.892 294.227C244.293 293.8 242.924 293.45 242.849 293.45C242.774 293.45 242.712 293.09 242.712 292.649C242.712 290.956 240.677 289.992 239.448 291.104C238.382 292.069 233.233 289.139 233.578 287.765C234.001 286.08 231.79 284.648 230.601 285.836C229.78 286.656 225.555 281.863 226.049 280.671C226.666 279.181 225.8 277.966 224.25 278.147C223.005 278.293 222.843 278.125 220.957 274.78C219.988 273.06 219.949 272.88 220.424 272.354C221.58 271.077 220.89 269.115 219.286 269.115C218.481 269.115 218.348 268.937 217.788 267.113C216.637 263.362 216.623 263.084 217.548 262.355C218.881 261.307 218.23 258.869 216.616 258.869C216.22 258.869 216.136 258.299 216.136 255.666C216.136 253.033 216.22 252.465 216.616 252.465C218.23 252.465 218.881 250.026 217.548 248.978C216.623 248.25 216.637 247.971 217.788 244.219C218.348 242.396 218.481 242.218 219.286 242.218C220.89 242.218 221.58 240.255 220.424 238.979C219.949 238.454 219.988 238.274 220.957 236.552C222.843 233.207 223.005 233.041 224.25 233.186C225.8 233.367 226.666 232.151 226.049 230.661C225.555 229.47 229.78 224.676 230.601 225.497C231.79 226.686 234.001 225.252 233.578 223.569C233.233 222.193 238.382 219.264 239.448 220.228C240.658 221.324 242.712 220.383 242.712 218.734C242.712 218.096 242.985 217.906 244.553 217.459C248.63 216.296 248.772 216.279 249.125 216.94C249.929 218.442 252.109 218.346 252.499 216.793C252.616 216.325 252.982 215.943 253.389 215.863C254.52 215.643 257.29 215.628 258.336 215.836ZM255.84 219.394C255.84 220.106 255.61 224.418 255.329 228.973C254.854 236.649 254.874 240.848 255.402 245.98C255.598 247.876 255.572 247.982 254.924 247.982C254.547 247.982 254.236 247.874 254.231 247.742C254.12 244.094 246.685 217.755 246.566 220.588C246.487 222.494 250.904 241.298 252.168 244.428C253.322 247.289 253.549 248.136 253.219 248.345C252.474 248.817 252.244 248.493 250.557 244.603C249.138 241.331 239.503 225.818 237.841 224.127C236.46 222.723 246.957 242.506 249.176 245.49C250.579 247.377 251.637 249.07 251.524 249.252C251.058 250.005 250.317 249.429 248.041 246.547C245.964 243.917 230.223 229.214 230.223 229.904C230.223 230.652 244.234 245.603 246.947 247.748C249.742 249.96 250.054 250.307 249.751 250.873C249.432 251.468 249.213 251.359 246.301 249.159C243.739 247.222 222.035 235.61 223.695 237.064C225.847 238.947 242.241 249.083 245.193 250.354C248.584 251.815 249.471 252.546 248.366 252.969C248.131 253.06 246.365 252.494 244.444 251.714C241.412 250.48 223.409 246.272 221.732 246.405C220.189 246.528 240.768 252.842 244.218 253.305C247.995 253.811 248.155 253.864 248.155 254.59C248.155 255.47 248.326 255.46 243.992 254.864C240.684 254.409 220.938 255.097 220.938 255.666C220.938 256.237 240.684 256.924 243.992 256.469C248.326 255.874 248.155 255.862 248.155 256.744C248.155 257.47 247.995 257.522 244.218 258.028C240.768 258.49 220.189 264.804 221.732 264.927C223.409 265.061 241.412 260.854 244.444 259.62C246.365 258.838 248.131 258.274 248.366 258.363C249.471 258.788 248.584 259.519 245.193 260.979C242.241 262.25 225.847 272.386 223.695 274.27C222.035 275.724 243.739 264.112 246.301 262.175C249.213 259.973 249.432 259.865 249.751 260.461C250.054 261.027 249.742 261.374 246.947 263.586C244.234 265.731 230.223 280.681 230.223 281.43C230.223 282.12 245.964 267.417 248.041 264.786C250.317 261.904 251.058 261.329 251.524 262.082C251.637 262.263 250.579 263.957 249.176 265.843C246.957 268.826 236.46 288.61 237.841 287.207C239.503 285.516 249.138 270.002 250.557 266.73C252.244 262.839 252.474 262.517 253.219 262.988C253.549 263.198 253.321 264.045 252.165 266.906C250.9 270.035 246.514 288.691 246.564 290.728C246.637 293.733 254.12 267.253 254.231 263.592C254.236 263.46 254.527 263.351 254.879 263.351C255.644 263.351 255.651 263.468 255.144 268.329C254.833 271.312 254.867 273.762 255.343 282.454C255.866 291.995 256.16 295.409 256.16 291.94C256.16 291.227 256.39 286.916 256.671 282.361C257.146 274.684 257.126 270.486 256.598 265.353C256.402 263.458 256.428 263.351 257.076 263.351C257.453 263.351 257.764 263.46 257.769 263.592C257.88 267.24 265.315 293.578 265.434 290.746C265.513 288.84 261.096 270.034 259.832 266.906C258.678 264.044 258.451 263.198 258.781 262.988C259.528 262.515 259.768 262.848 261.345 266.536C262.669 269.631 272.552 285.573 274.159 287.207C275.539 288.608 265.043 268.827 262.824 265.843C261.421 263.957 260.364 262.263 260.476 262.082C260.942 261.328 261.683 261.905 263.967 264.796C266.056 267.441 280.873 281.283 281.614 281.283C282.326 281.283 267.811 265.76 265.06 263.579C262.278 261.372 261.953 261.011 262.252 260.455C262.566 259.867 262.803 259.986 265.729 262.203C268.421 264.242 288.872 275.082 287.379 273.68C285.615 272.021 269.836 262.276 266.807 260.974C264.826 260.124 263.205 259.313 263.205 259.175C263.205 257.934 263.58 257.956 266.993 259.395C269.862 260.606 290.301 265.449 291.692 265.248C292.879 265.077 271.037 258.469 267.767 258.01C264.047 257.489 263.845 257.422 263.845 256.723C263.845 255.865 263.642 255.877 268.168 256.466C271.631 256.915 291.382 256.236 291.382 255.666C291.382 255.097 271.631 254.417 268.168 254.867C263.642 255.456 263.845 255.468 263.845 254.61C263.845 253.911 264.047 253.845 267.767 253.324C271.027 252.866 292.918 246.242 291.692 246.083C290.248 245.896 269.856 250.73 266.993 251.938C263.58 253.378 263.205 253.399 263.205 252.159C263.205 252.019 264.826 251.209 266.807 250.358C269.836 249.058 285.615 239.313 287.379 237.653C288.872 236.251 268.421 247.091 265.729 249.13C262.803 251.346 262.566 251.465 262.252 250.879C261.953 250.322 262.278 249.961 265.06 247.754C267.771 245.604 281.777 230.649 281.777 229.904C281.777 229.214 266.036 243.917 263.959 246.547C261.683 249.429 260.942 250.005 260.476 249.252C260.364 249.07 261.421 247.377 262.824 245.49C265.043 242.506 275.539 222.725 274.159 224.127C272.552 225.76 262.669 241.703 261.345 244.798C259.768 248.485 259.528 248.818 258.781 248.345C258.451 248.136 258.678 247.289 259.832 244.428C261.096 241.298 265.513 222.494 265.434 220.588C265.315 217.755 257.88 244.094 257.769 247.742C257.764 247.874 257.473 247.982 257.121 247.982C256.356 247.982 256.349 247.866 256.856 243.004C257.167 240.022 257.133 237.572 256.657 228.88C256.134 219.338 255.84 215.923 255.84 219.394Z" fill="#05058C"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="M251.437 210.42C251.745 210.499 252.25 210.499 252.558 210.42C252.867 210.339 252.614 210.272 251.997 210.272C251.38 210.272 251.128 210.339 251.437 210.42ZM259.442 210.42C259.75 210.499 260.255 210.499 260.563 210.42C260.872 210.339 260.62 210.272 260.003 210.272C259.386 210.272 259.133 210.339 259.442 210.42ZM254.792 215.872C255.36 215.944 256.369 215.945 257.033 215.875C257.697 215.806 257.233 215.748 256 215.747C254.767 215.746 254.223 215.802 254.792 215.872ZM255.607 221.726C255.607 222.518 255.67 222.842 255.745 222.447C255.822 222.05 255.822 221.401 255.745 221.005C255.67 220.608 255.607 220.934 255.607 221.726ZM256.247 221.726C256.247 222.518 256.31 222.842 256.387 222.447C256.462 222.05 256.462 221.401 256.387 221.005C256.31 220.608 256.247 220.934 256.247 221.726ZM236.686 222.526C236.887 222.966 237.175 223.327 237.327 223.327C237.478 223.327 237.367 222.966 237.079 222.526C236.79 222.086 236.502 221.726 236.438 221.726C236.374 221.726 236.485 222.086 236.686 222.526ZM255.287 227.49C255.287 228.282 255.35 228.606 255.425 228.209C255.502 227.814 255.502 227.165 255.425 226.769C255.35 226.372 255.287 226.696 255.287 227.49ZM256.567 227.49C256.567 228.282 256.63 228.606 256.707 228.209C256.782 227.814 256.782 227.165 256.707 226.769C256.63 226.372 256.567 226.696 256.567 227.49ZM229.262 229.248C229.676 229.689 230.084 229.978 230.17 229.891C230.382 229.679 229.247 228.45 228.837 228.45C228.658 228.45 228.849 228.809 229.262 229.248ZM282.254 229.092C281.399 230.038 281.857 230.187 282.738 229.248C283.151 228.809 283.342 228.45 283.163 228.45C282.982 228.45 282.574 228.739 282.254 229.092ZM254.967 232.932C254.967 233.725 255.028 234.05 255.105 233.653C255.182 233.257 255.182 232.608 255.105 232.212C255.028 231.816 254.967 232.14 254.967 232.932ZM256.888 232.932C256.888 233.725 256.95 234.05 257.027 233.653C257.103 233.257 257.103 232.608 257.027 232.212C256.95 231.816 256.888 232.14 256.888 232.932ZM254.659 239.176C254.66 240.233 254.72 240.626 254.792 240.052C254.862 239.476 254.861 238.612 254.788 238.13C254.715 237.649 254.656 238.12 254.659 239.176ZM257.22 239.176C257.221 240.233 257.281 240.626 257.353 240.052C257.425 239.476 257.422 238.612 257.349 238.13C257.276 237.649 257.219 238.12 257.22 239.176ZM218.697 245.698C219.476 246.161 220.824 246.499 220.458 246.138C220.282 245.965 219.706 245.731 219.177 245.617C218.55 245.483 218.383 245.511 218.697 245.698ZM210.487 255.666C210.487 257.339 210.541 258.024 210.607 257.188C210.673 256.351 210.673 254.983 210.607 254.146C210.541 253.31 210.487 253.993 210.487 255.666ZM301.423 255.666C301.423 257.339 301.477 258.024 301.544 257.188C301.61 256.351 301.61 254.983 301.544 254.146C301.477 253.31 301.423 253.993 301.423 255.666ZM235.588 254.612C235.983 254.688 236.632 254.688 237.028 254.612C237.425 254.536 237.101 254.473 236.307 254.473C235.515 254.473 235.191 254.536 235.588 254.612ZM275.292 254.612C275.688 254.688 276.337 254.688 276.733 254.612C277.129 254.536 276.805 254.473 276.013 254.473C275.22 254.473 274.895 254.536 275.292 254.612ZM230.144 254.932C230.54 255.008 231.188 255.008 231.585 254.932C231.981 254.856 231.657 254.793 230.865 254.793C230.072 254.793 229.747 254.856 230.144 254.932ZM280.9 254.935C281.386 255.01 282.107 255.007 282.501 254.932C282.895 254.856 282.496 254.796 281.617 254.797C280.736 254.8 280.413 254.863 280.9 254.935ZM224.38 255.253C224.777 255.328 225.425 255.328 225.821 255.253C226.217 255.176 225.893 255.113 225.101 255.113C224.308 255.113 223.983 255.176 224.38 255.253ZM286.499 255.253C286.895 255.328 287.544 255.328 287.94 255.253C288.337 255.176 288.012 255.113 287.219 255.113C286.427 255.113 286.103 255.176 286.499 255.253ZM218.377 255.666C218.377 255.843 218.953 255.986 219.657 255.986C220.362 255.986 220.938 255.843 220.938 255.666C220.938 255.491 220.362 255.346 219.657 255.346C218.953 255.346 218.377 255.491 218.377 255.666ZM291.382 255.666C291.382 255.843 292.031 255.986 292.823 255.986C293.615 255.986 294.264 255.843 294.264 255.666C294.264 255.491 293.615 255.346 292.823 255.346C292.031 255.346 291.382 255.491 291.382 255.666ZM224.38 256.213C224.777 256.29 225.425 256.29 225.821 256.213C226.217 256.136 225.893 256.075 225.101 256.075C224.308 256.075 223.983 256.136 224.38 256.213ZM286.499 256.213C286.895 256.29 287.544 256.29 287.94 256.213C288.337 256.136 288.012 256.075 287.219 256.075C286.427 256.075 286.103 256.136 286.499 256.213ZM230.144 256.533C230.54 256.61 231.188 256.61 231.585 256.533C231.981 256.457 231.657 256.395 230.865 256.395C230.072 256.395 229.747 256.457 230.144 256.533ZM280.9 256.537C281.386 256.611 282.107 256.608 282.501 256.533C282.895 256.456 282.496 256.396 281.617 256.399C280.736 256.401 280.413 256.464 280.9 256.537ZM235.588 256.853C235.983 256.93 236.632 256.93 237.028 256.853C237.425 256.777 237.101 256.715 236.307 256.715C235.515 256.715 235.191 256.777 235.588 256.853ZM275.292 256.853C275.688 256.93 276.337 256.93 276.733 256.853C277.129 256.777 276.805 256.715 276.013 256.715C275.22 256.715 274.895 256.777 275.292 256.853ZM219.177 265.434L218.217 265.887L219.177 265.699C219.706 265.595 220.274 265.385 220.442 265.232C220.899 264.813 220.287 264.911 219.177 265.434ZM254.659 272.157C254.66 273.214 254.72 273.607 254.792 273.032C254.862 272.456 254.861 271.592 254.788 271.111C254.715 270.63 254.656 271.101 254.659 272.157ZM257.22 272.157C257.221 273.214 257.281 273.607 257.353 273.032C257.425 272.456 257.422 271.592 257.349 271.111C257.276 270.63 257.219 271.101 257.22 272.157ZM254.967 278.4C254.967 279.194 255.028 279.518 255.105 279.121C255.182 278.726 255.182 278.077 255.105 277.681C255.028 277.284 254.967 277.608 254.967 278.4ZM256.888 278.4C256.888 279.194 256.95 279.518 257.027 279.121C257.103 278.726 257.103 278.077 257.027 277.681C256.95 277.284 256.888 277.608 256.888 278.4ZM229.262 282.084C228.849 282.525 228.658 282.884 228.837 282.884C229.247 282.884 230.382 281.654 230.17 281.442C230.084 281.356 229.676 281.645 229.262 282.084ZM282.097 282.083C282.51 282.523 282.993 282.884 283.168 282.884C283.345 282.884 283.15 282.523 282.737 282.083C282.323 281.643 281.841 281.283 281.664 281.283C281.489 281.283 281.683 281.643 282.097 282.083ZM255.287 283.844C255.287 284.637 255.35 284.962 255.425 284.565C255.502 284.168 255.502 283.52 255.425 283.124C255.35 282.728 255.287 283.052 255.287 283.844ZM256.567 283.844C256.567 284.637 256.63 284.962 256.707 284.565C256.782 284.168 256.782 283.52 256.707 283.124C256.63 282.728 256.567 283.052 256.567 283.844ZM221.258 285.225C221.258 285.28 221.727 285.749 222.299 286.266L223.34 287.207L222.399 286.166C221.522 285.196 221.258 284.978 221.258 285.225ZM236.686 288.808C236.485 289.247 236.374 289.608 236.438 289.608C236.502 289.608 236.79 289.247 237.079 288.808C237.367 288.368 237.478 288.007 237.327 288.007C237.175 288.007 236.887 288.368 236.686 288.808ZM255.607 289.608C255.607 290.4 255.67 290.724 255.745 290.329C255.822 289.932 255.822 289.284 255.745 288.887C255.67 288.491 255.607 288.816 255.607 289.608ZM256.247 289.608C256.247 290.4 256.31 290.724 256.387 290.329C256.462 289.932 256.462 289.284 256.387 288.887C256.31 288.491 256.247 288.816 256.247 289.608ZM254.792 295.602C255.36 295.674 256.369 295.674 257.033 295.605C257.697 295.536 257.233 295.478 256 295.477C254.767 295.476 254.223 295.532 254.792 295.602Z" fill="#5A5AB4"/>
</svg>`

Hope this helps your project @LeCoupa

**Comment by LeCoupa** [comment]
Thank you so much @Ruchirr
